# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LaterChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LaterChat
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'ART',
  ]

  target 'LaterChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LaterChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LaterChat-tvOS

  target 'LaterChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
